### ISSUE TITLE
Literal 'M' is not a valid value for enumeration 'AdministrativeGender'

### ISSUE THREAD

**Issue by joshmouch** [ewoutkramer/fhir-net-api#246]
Using FHIR.Net version .90.6-alpha4, when I am fetching Patient resource, I get the following exception:

``
System.FormatException: At line -1, pos -1: Literal 'M' is not a valid value for enumeration 'AdministrativeGender'
   at Hl7.Fhir.Serialization.ComplexTypeReader.read(ClassMapping mapping, IEnumerable`1 members, Base existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.Deserialize(ClassMapping mapping, Base existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.read(ClassMapping mapping, IEnumerable`1 members, Base existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.Deserialize(ClassMapping mapping, Base existing)
   at Hl7.Fhir.Serialization.ResourceReader.Deserialize(Resource existing)
   at Hl7.Fhir.Serialization.FhirJsonParser.Parse[T](String json)
   at Hl7.Fhir.Rest.HttpToEntryExtensions.parseResource(String bodyText, String contentType)
   at Hl7.Fhir.Rest.HttpToEntryExtensions.ToBundleEntry(HttpWebResponse response, Byte[] body)
   at Hl7.Fhir.Rest.Requester.Execute(EntryComponent interaction)
   at Hl7.Fhir.Rest.FhirClient.execute[TResource](Bundle tx, IEnumerable`1 expect)
``

I looked up the correct enumeration values here, and 'M' seems to be correct.

https://www.hl7.org/fhir/valueset-administrative-gender.html

**Comment by cknaap** [comment]
On the page you link to I can see 'M' as a valid value in v2 and v3, but not in FHIR. It should be 'male'. See the table under '1.25.2.1.1.1 Content Logical Definition', the Code column.
