### ISSUE TITLE
FetchConformance() Unit Test Fails: OperationOutcome included in the body.

### ISSUE THREAD

**Issue by pkjordan** [ewoutkramer/fhir-net-api#79]
Assembly version 0.50.2

Using Graham's DSTU2 Server ()...
Uri testEndpoint = new Uri("http://fhir-dev.healthintersections.com.au/open");

Result Message:	
Test method Hl7.Fhir.Tests.Rest.FhirClientTests.FetchConformance threw exception: 
Hl7.Fhir.Rest.FhirOperationException: Operation returned unexpected status InternalServerError, an OperationOutcome was included in the body
Result StackTrace:	
at Hl7.Fhir.Rest.Requester.Execute[TResource](Bundle transaction, IEnumerable`1 expect) in Hl7.Fhir.Core\Rest\Requester.cs:line 98
   at Hl7.Fhir.Rest.Requester.Execute[TResource](Bundle transaction, HttpStatusCode expect) in Hl7.Fhir.Core\Rest\Requester.cs:line 108
   at Hl7.Fhir.Rest.FhirClient.Conformance() in Projects\Hl7.Fhir.Core\Rest\FhirClient.cs:line 331
   at Hl7.Fhir.Tests.Rest.FhirClientTests.FetchConformance() in Hl7.Fhir.Core.Tests\Rest\FhirClientTests.cs:line 50

Several other UTs also fail with this exception. Will be at Connectathon on Saturday if you'd like to see this.

Cheers, Peter J (HL7 NZ)

**Comment by ewoutkramer** [comment]
Must have been an error on Grahame's server, because it works today!  I did improve the error message so it will now show the actual outcome, instead of just stating it is included in the body.
