### ISSUE TITLE
Empty contained block leads to `NullReferenceException` in 1.0.0

### ISSUE THREAD

**Issue by hannni** [ewoutkramer/fhir-net-api#814]
The following code:
```csharp
var xml = "<Patient xmlns='http://hl7.org/fhir'><contained></contained></Patient>";
var parser = new FhirXmlParser();
var parsedPatient = parser.Parse<Patient>(xml);
```

leads to the following `NullReferenceException`:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Hl7.Fhir.Introspection.ModelInspector.buildResourceKey(String name, String profile)
   at Hl7.Fhir.Introspection.ModelInspector.FindClassMappingForResource(String name, String profile)
   at Hl7.Fhir.Serialization.ResourceReader.Deserialize(Resource existing)
   at Hl7.Fhir.Serialization.RepeatingElementReader.Deserialize(PropertyMapping prop, String memberName, IList existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.read(ClassMapping mapping, IEnumerable`1 members, Base existing)
   at Hl7.Fhir.Serialization.ComplexTypeReader.Deserialize(ClassMapping mapping, Base existing)
   at Hl7.Fhir.Serialization.ResourceReader.Deserialize(Resource existing)
   at Hl7.Fhir.Serialization.PocoBuilder.buildInternal(ISourceNode source, Type typeToBuild)
   at Hl7.Fhir.Serialization.FhirXmlParser.Parse[T](String xml)
```

I would have expected something like a `FormatException` instead.

**Comment by ewoutkramer** [comment]
Yeah, you are right to expect that ;-)

**Comment by ewoutkramer** [comment]
This is fixed as part of other refactorings in version 1.2
