### ISSUE TITLE
DocumentReference Create

### ISSUE THREAD

**Issue by rtaixghealth** [ewoutkramer/fhir-net-api#95]
I'm getting the following error and stack trace:

Error:
Cannot parse xml: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

Stack:
   at Hl7.Fhir.Rest.HttpToEntryExtensions.parseResource(String bodyText, String contentType) in c:\Git\fhir-net-api\src\Hl7.Fhir.Core\Rest\HttpToEntryExtensions.cs:line 164
   at Hl7.Fhir.Rest.HttpToEntryExtensions.ToBundleEntry(HttpWebResponse response) in c:\Git\fhir-net-api\src\Hl7.Fhir.Core\Rest\HttpToEntryExtensions.cs:line 65
   at Hl7.Fhir.Rest.Requester.doRequest(BundleEntryComponent interaction) in c:\Git\fhir-net-api\src\Hl7.Fhir.Core\Rest\Requester.cs:line 128
   at Hl7.Fhir.Rest.Requester.Execute[TResource](Bundle transaction, IEnumerable`1 expect) in c:\Git\fhir-net-api\src\Hl7.Fhir.Core\Rest\Requester.cs:line 59
   at Hl7.Fhir.Rest.FhirClient.Create[TResource](TResource resource) in c:\Git\fhir-net-api\src\Hl7.Fhir.Core\Rest\FhirClient.cs:line 303
   at Persistence.Core.Fhir.DAL.BaseFhirDAL.CreateItem[S,T](T item, String itemId) in c:\TFS\Developer.App.Client\PersistenceFramework\EnrGFramework-Fhir1\Persistence\Core\Fhir\DAL\BaseFhirDAL.cs:line 288

Please advise.

Thanks!

**Comment by rtaixghealth** [comment]
I have tried different variations and even tried bare minimal of adding an attachment but no data, yet, it's coming back with the same error.

Previous post was using the DSTU2 library HL7 FHIR Core 0.50.1.

I have since upgraded to HL7 FHIR Core 0.50.2-alpha3.  It now hits the FHIR server with a status 500 Internal Error, which is a step further than the previous post.  However, in both cases, I still get the DTD error from the library.

The content of XMLFile2.xml is the sample xml from MSDN [https://msdn.microsoft.com/en-us/library/ms762271(v=vs.85).aspx]

![8-25-2015 9-03-20 pm](https://cloud.githubusercontent.com/assets/13961469/9485334/e1a6f25e-4b6c-11e5-8f08-951f5d634866.png)

Please advise.

Thanks!

**Comment by ewoutkramer** [comment]
Although the error handling has been improved to give better feedback (although I think in alpha4), the cause remains the same: the server is not handling the request the way it should and returns a neat HTML page with an error message instead of a FHIR payload.

Many times this happens when you have chosen the wrong endpoint (e.g. http://fhir-dev.healthintersections.com.au/ instead of http://fhir-dev.healthintersections.com.au/open).

Is it possible for you to trace this in Fiddler/Postman (e.g. have a recording of the outgoing request and response in a file), that would make it easier to trace the cause.

**Comment by rtaixghealth** [comment]
Hi Ewout, 

Thank you for your quick response.

It was the reason as you've mentioned, the endpoint was returning an HTML page with an error message.

There was an issue on the FHIR server, the mapping for the object was incorrect, causing a 500 Internal Error.  They're putting in a fix for this.

Thank you,

-rubes
